# Load the library

In [1]:
import pandas as pd
import numpy as np

# Load Dataset

In [3]:
# reading ratings file:
r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
rating = pd.read_csv('ml-100k/u.data', sep='\t', names=r_cols,encoding='latin-1')

In [4]:
rating.head(5)

   user_id  movie_id  rating  unix_timestamp
0      196       242       3       881250949
1      186       302       3       891717742
2       22       377       1       878887116
3      244        51       2       880606923
4      166       346       1       886397596

In [7]:
rating.user_id.unique().shape[0]

943

In [8]:
rating.movie_id.unique().shape[0]

1682

# Create pivot table for user and movie basedon ratings

In [10]:
data_matrix=rating.pivot_table(index='user_id',columns='movie_id',values='rating')

In [11]:
data_matrix

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
#Replace NaN with 0
data_matrix=data_matrix.replace(np.nan,0)

In [16]:
data_matrix.T

user_id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
movie_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,4.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,4.0,...,2.0,3.0,4.0,0.0,4.0,0.0,0.0,5.0,0.0,0.0
2,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,4.0,...,5.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
5,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1679,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1681,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1682,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Find Cosine Similatity for user and Item

In [17]:
from sklearn.metrics.pairwise import pairwise_distances 
item_similarity = pairwise_distances(data_matrix.T, metric='cosine')

# Using formula for user and item we are calcuating the score value

In [18]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        #We use np.newaxis so that mean_user_rating has same format as ratings
        ratings_diff = (ratings - mean_user_rating[:, np.newaxis])
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
      #  ratings.dot(similarity) computes the weighted sum of ratings, where the weights are the item similarities.
      # np.abs(similarity).sum(axis=1) calculates the sum of absolute similarities for normalization.
      #The resulting prediction directly gives the predicted ratings based on item similarities.
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [21]:
item_prediction=predict(data_matrix,item_similarity,type='item')

In [22]:
item_prediction

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.446278,0.475473,0.505938,0.443633,0.512667,0.547939,0.446243,0.463059,0.474916,0.515821,...,0.580579,0.576202,0.582478,0.582478,0.575717,0.588155,0.588155,0.588155,0.573107,0.566696
2,0.108544,0.132957,0.125589,0.124932,0.131178,0.129005,0.110883,0.122223,0.109599,0.121525,...,0.135490,0.136546,0.134829,0.134829,0.134108,0.134458,0.134458,0.134458,0.136576,0.137111
3,0.085685,0.091690,0.087643,0.089966,0.089658,0.089985,0.083492,0.089725,0.085188,0.088331,...,0.089770,0.090506,0.086261,0.086261,0.089201,0.084659,0.084659,0.084659,0.089768,0.090845
4,0.053693,0.059604,0.058114,0.058364,0.059356,0.061472,0.053374,0.058615,0.055905,0.060601,...,0.061349,0.061686,0.061195,0.061195,0.060693,0.057937,0.057937,0.057937,0.061673,0.062281
5,0.224739,0.229171,0.263280,0.226387,0.259973,0.296529,0.232710,0.237109,0.258581,0.275076,...,0.297628,0.295990,0.299922,0.299922,0.298188,0.302051,0.302051,0.302051,0.293373,0.294309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.092574,0.113870,0.110211,0.112040,0.112768,0.123140,0.098578,0.110839,0.098858,0.118579,...,0.123829,0.124430,0.120776,0.120776,0.121360,0.125056,0.125056,0.125056,0.123470,0.124327
940,0.164358,0.184894,0.196502,0.164884,0.195860,0.209652,0.162840,0.165606,0.171761,0.194536,...,0.217536,0.215515,0.219136,0.219136,0.216173,0.218583,0.218583,0.218583,0.216582,0.216819
941,0.032300,0.045024,0.042924,0.043223,0.047493,0.051077,0.032761,0.042646,0.039399,0.047421,...,0.052762,0.053042,0.052692,0.052692,0.051514,0.053028,0.053028,0.053028,0.051910,0.052280
942,0.157779,0.174095,0.189000,0.163514,0.186140,0.194151,0.164910,0.156970,0.167038,0.181295,...,0.197537,0.194479,0.198479,0.198479,0.197969,0.199793,0.199793,0.199793,0.197394,0.200031
943,0.247672,0.244892,0.282630,0.241440,0.279338,0.335121,0.250015,0.263325,0.273579,0.313885,...,0.336816,0.338652,0.338585,0.338585,0.336956,0.344104,0.344104,0.344104,0.330514,0.331025

# As per User based filtering ,first have to find similarity between the input user and others

In [23]:
#1. Select input user

input_item=50

In [24]:
#Create dataframe for item similarity
item_similarity_df=pd.DataFrame(item_similarity)

In [26]:
item_similarity_df.

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,2.220446e-16,5.976178e-01,0.669755,5.450621e-01,0.713286,0.883656,0.379021,0.518886,0.503712,0.726065,...,0.964613,1.0,1.000000,1.000000,0.964613,1.0,1.0,1.0,0.952817,0.952817
1,5.976178e-01,2.220446e-16,0.726931,4.974292e-01,0.681164,0.916437,0.616597,0.662998,0.744748,0.828918,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,0.921701,0.921701
2,6.697552e-01,7.269308e-01,0.000000,6.751336e-01,0.787043,0.893278,0.627079,0.799206,0.726331,0.841896,...,1.000000,1.0,1.000000,1.000000,0.967708,1.0,1.0,1.0,1.000000,0.903125
3,5.450621e-01,4.974292e-01,0.675134,1.110223e-16,0.665761,0.909692,0.510717,0.509764,0.580956,0.747439,...,1.000000,1.0,0.905978,0.905978,0.962391,1.0,1.0,1.0,0.943587,0.924782
4,7.132865e-01,6.811638e-01,0.787043,6.657605e-01,0.000000,0.962701,0.665231,0.740839,0.727552,0.944547,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.000000,0.905789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1678,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1679,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.000000,1.000000
1680,9.528169e-01,9.217006e-01,1.000000,9.435867e-01,1.000000,1.000000,0.948502,0.917967,0.942640,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,0.000000,1.000000
1681,9.528169e-01,9.217006e-01,0.903125,9.247823e-01,0.905789,1.000000,0.948502,1.000000,0.928300,1.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.000000,0.000000

In [39]:
#Select top 5 similiarity for item based on input item
similiar_input_item=item_similarity_df[input_item].sort_values(ascending=True).head(5).index

In [40]:
similiar_input_item

Index([50, 401, 738, 450, 548], dtype='int64')

In [63]:
#to check the user_id for each similiar input item
similiar_input_item_list=[]
for movie_id in similiar_input_item:
     mov_id=list(rating[rating['movie_id']==movie_id]['user_id'])
     similiar_input_item_list.append(mov_id)

In [64]:
similiar_input_item_list

[[290,
  79,
  2,
  8,
  274,
  227,
  99,
  305,
  108,
  63,
  234,
  97,
  117,
  70,
  318,
  145,
  124,
  253,
  271,
  254,
  326,
  213,
  80,
  322,
  28,
  267,
  130,
  262,
  230,
  316,
  327,
  299,
  144,
  162,
  48,
  141,
  251,
  297,
  137,
  154,
  257,
  269,
  123,
  94,
  330,
  368,
  77,
  321,
  381,
  43,
  286,
  247,
  68,
  150,
  214,
  210,
  158,
  279,
  288,
  280,
  25,
  102,
  209,
  103,
  398,
  379,
  409,
  386,
  407,
  101,
  201,
  203,
  283,
  128,
  200,
  58,
  54,
  311,
  96,
  4,
  401,
  71,
  59,
  176,
  393,
  14,
  12,
  432,
  378,
  245,
  115,
  406,
  444,
  160,
  23,
  433,
  125,
  320,
  438,
  461,
  250,
  437,
  119,
  27,
  275,
  389,
  445,
  270,
  422,
  465,
  467,
  157,
  276,
  65,
  10,
  435,
  458,
  478,
  6,
  192,
  387,
  405,
  287,
  64,
  369,
  272,
  394,
  334,
  346,
  352,
  177,
  153,
  62,
  148,
  325,
  15,
  456,
  371,
  506,
  360,
  509,
  533,
  454,
  340,
  239,
  221,
  215,
  194,
  45,
  5,
  479,
  303,
  494,
  504,
  347,
  161,
  313,
  113,
  453,
  540,
  402,
  66,
  523,
  536,
  527,
  277,
  549,
  551,
  530,
  339,
  49,
  539,
  581,
  484,
  294,
  592,
  463,
  217,
  87,
  91,
  417,
  569,
  498,
  293,
  46,
  495,
  385,
  69,
  248,
  399,
  528,
  382,
  151,
  416,
  37,
  345,
  470,
  411,
  244,
  350,
  623,
  516,
  430,
  493,
  624,
  517,
  370,
  268,
  324,
  638,
  563,
  178,
  618,
  26,
  642,
  653,
  354,
  60,
  644,
  496,
  184,
  650,
  30,
  457,
  343,
  552,
  600,
  263,
  662,
  471,
  602,
  363,
  541,
  481,
  421,
  597,
  503,
  550,
  521,
  89,
  629,
  189,
  672,
  182,
  622,
  323,
  582,
  654,
  682,
  426,
  619,
  235,
  608,
  526,
  698,
  660,
  1,
  308,
  637,
  575,
  694,
  634,
  474,
  705,
  169,
  310,
  499,
  719,
  594,
  505,
  490,
  488,
  557,
  72,
  537,
  296,
  721,
  704,
  175,
  655,
  730,
  482,
  21,
  429,
  676,
  736,
  233,
  758,
  710,
  674,
  413,
  500,
  757,
  116,
  13,
  593,
  708,
  373,
  55,
  424,
  395,
  374,
  663,
  573,
  524,
  706,
  691,
  711,
  174,
  475,
  104,
  751,
  576,
  794,
  700,
  236,
  610,
  513,
  678,
  53,
  703,
  487,
  367,
  768,
  714,
  42,
  659,
  630,
  301,
  799,
  198,
  797,
  564,
  658,
  761,
  132,
  231,
  216,
  826,
  746,
  835,
  862,
  791,
  292,
  85,
  727,
  825,
  392,
  760,
  419,
  337,
  864,
  748,
  701,
  744,
  643,
  753,
  92,
  833,
  51,
  747,
  265,
  717,
  397,
  851,
  295,
  669,
  880,
  514,
  883,
  561,
  830,
  632,
  664,
  844,
  56,
  641,
  789,
  891,
  507,
  697,
  742,
  881,
  466,
  716,
  871,
  44,
  831,
  931,
  391,
  846,
  468,
  82,
  934,
  815,
  256,
  902,
  298,
  450,
  665,
  917,
  869,
  776,
  919,
  689,
  567,
  512,
  878,
  834,
  867,
  796,
  9,
  868,
  480,
  344,
  329,
  806,
  671,
  649,
  249,
  380,
  621,
  185,
  455,
  606,
  699,
  127,
  483,
  839,
  790,
  312,
  121,
  916,
  679,
  668,
  922,
  892,
  232,
  246,
  436,
  222,
  452,
  854,
  895,
  548,
  897,
  57,
  852,
  546,
  709,
  22,
  765,
  936,
  805,
  766,
  770,
  580,
  613,
  882,
  875,
  459,
  291,
  712,
  899,
  562,
  555,
  889,
  595,
  896,
  586,
  684,
  763,
  601,
  942,
  741,
  756,
  890,
  633,
  840,
  359,
  735,
  447,
  843,
  850,
  188,
  745,
  764,
  738,
  680,
  553,
  603,
  554,
  870,
  804,
  328,
  773,
  197,
  18,
  32,
  566,
  645,
  20,
  577,
  486,
  823,
  759,
  579,
  879,
  7,
  940,
  793,
  938,
  625,
  910,
  894,
  620,
  901,
  798,
  332,
  781,
  908,
  848,
  885,
  686,
  795,
  807,
  183,
  425,
  786,
  937,
  887,
  666,
  588,
  596,
  907,
  933,
  464,
  95,
  41,
  545,
  109,
  715,
  913,
  403,
  723,
  538,
  83,
  307,
  472,
  542,
  924,
  929,
  930,
  560,
  535,
  923,
  800,
  336,
  508,
  693,
  661,
  361,
  921,
  120,
  832,
  943,
  782,
  785,
  893,
  584,
  847,
  838,
  774,
  771,
  497,
  779,
  648,
  734,
  749,
  886,
  739,
  903,
  780],
 [301,
  87,
  7,
  62,
  276,
  264,
  295,
  222,
  318,
  293,
  234,
  269,
  379,
  49,
  291,
  442,
  472,
  378,
  336,
  389,
  94,
  5,
  450,
  110,
  307,
  373,
  279,
  13,
  184,
  563,
  200,
  244,
  246,
  453,
  125,
  174,
  38,
  621,
  416,
  314,
  684,
  727,
  796,
  711,
  790,
  399,
  741,
  457,
  881,
  11,
  286,
  823,
  303,
  642,
  435,
  712,
  476,
  804,
  846,
  92,
  405,
  774,
  870,
  864,
  892,
  152,
  927,
  542,
  437,
  833,
  504,
  880,
  805,
  749,
  682,
  943],
 [303,
  94,
  286,
  56,
  336,
  416,
  49,
  244,
  455,
  268,
  145,
  184,
  295,
  399,
  11,
  476,
  345,
  790,
  778,
  868,
  712,
  682,
  222,
  927,
  763,
  877,
  405,
  751,
  442,
  709,
  846],
 [56,
  303,
  215,
  334,
  38,
  194,
  307,
  7,
  295,
  276,
  290,
  127,
  405,
  374,
  394,
  28,
  337,
  183,
  13,
  267,
  222,
  130,
  145,
  533,
  102,
  44,
  92,
  378,
  70,
  158,
  483,
  532,
  332,
  664,
  600,
  457,
  399,
  275,
  5,
  807,
  437,
  757,
  843,
  497,
  545,
  638,
  603,
  774,
  279,
  584,
  417,
  823,
  650,
  943,
  622,
  268,
  896,
  922,
  95,
  442,
  796,
  536,
  702],
 [13, 7, 254, 102, 405, 498, 325, 472, 911, 774, 504, 887]]

In [65]:
#6. Convert all the list as single
import itertools
similar_item_userid_single_list=list(itertools.chain.from_iterable(similiar_input_item_list))

In [66]:
similar_item_userid_single_list

[290,
 79,
 2,
 8,
 274,
 227,
 99,
 305,
 108,
 63,
 234,
 97,
 117,
 70,
 318,
 145,
 124,
 253,
 271,
 254,
 326,
 213,
 80,
 322,
 28,
 267,
 130,
 262,
 230,
 316,
 327,
 299,
 144,
 162,
 48,
 141,
 251,
 297,
 137,
 154,
 257,
 269,
 123,
 94,
 330,
 368,
 77,
 321,
 381,
 43,
 286,
 247,
 68,
 150,
 214,
 210,
 158,
 279,
 288,
 280,
 25,
 102,
 209,
 103,
 398,
 379,
 409,
 386,
 407,
 101,
 201,
 203,
 283,
 128,
 200,
 58,
 54,
 311,
 96,
 4,
 401,
 71,
 59,
 176,
 393,
 14,
 12,
 432,
 378,
 245,
 115,
 406,
 444,
 160,
 23,
 433,
 125,
 320,
 438,
 461,
 250,
 437,
 119,
 27,
 275,
 389,
 445,
 270,
 422,
 465,
 467,
 157,
 276,
 65,
 10,
 435,
 458,
 478,
 6,
 192,
 387,
 405,
 287,
 64,
 369,
 272,
 394,
 334,
 346,
 352,
 177,
 153,
 62,
 148,
 325,
 15,
 456,
 371,
 506,
 360,
 509,
 533,
 454,
 340,
 239,
 221,
 215,
 194,
 45,
 5,
 479,
 303,
 494,
 504,
 347,
 161,
 313,
 113,
 453,
 540,
 402,
 66,
 523,
 536,
 527,
 277,
 549,
 551,
 530,
 339,
 49,
 539,
 581,
 484,
 294,
 592,
 463,
 217,
 87,
 91,
 417,
 569,
 498,
 293,
 46,
 495,
 385,
 69,
 248,
 399,
 528,
 382,
 151,
 416,
 37,
 345,
 470,
 411,
 244,
 350,
 623,
 516,
 430,
 493,
 624,
 517,
 370,
 268,
 324,
 638,
 563,
 178,
 618,
 26,
 642,
 653,
 354,
 60,
 644,
 496,
 184,
 650,
 30,
 457,
 343,
 552,
 600,
 263,
 662,
 471,
 602,
 363,
 541,
 481,
 421,
 597,
 503,
 550,
 521,
 89,
 629,
 189,
 672,
 182,
 622,
 323,
 582,
 654,
 682,
 426,
 619,
 235,
 608,
 526,
 698,
 660,
 1,
 308,
 637,
 575,
 694,
 634,
 474,
 705,
 169,
 310,
 499,
 719,
 594,
 505,
 490,
 488,
 557,
 72,
 537,
 296,
 721,
 704,
 175,
 655,
 730,
 482,
 21,
 429,
 676,
 736,
 233,
 758,
 710,
 674,
 413,
 500,
 757,
 116,
 13,
 593,
 708,
 373,
 55,
 424,
 395,
 374,
 663,
 573,
 524,
 706,
 691,
 711,
 174,
 475,
 104,
 751,
 576,
 794,
 700,
 236,
 610,
 513,
 678,
 53,
 703,
 487,
 367,
 768,
 714,
 42,
 659,
 630,
 301,
 799,
 198,
 797,
 564,
 658,
 761,
 132,
 231,
 216,
 826,
 746,
 835,
 862,
 791,
 292,
 85,
 727,
 825,
 392,
 760,
 419,
 337,
 864,
 748,
 701,
 744,
 643,
 753,
 92,
 833,
 51,
 747,
 265,
 717,
 397,
 851,
 295,
 669,
 880,
 514,
 883,
 561,
 830,
 632,
 664,
 844,
 56,
 641,
 789,
 891,
 507,
 697,
 742,
 881,
 466,
 716,
 871,
 44,
 831,
 931,
 391,
 846,
 468,
 82,
 934,
 815,
 256,
 902,
 298,
 450,
 665,
 917,
 869,
 776,
 919,
 689,
 567,
 512,
 878,
 834,
 867,
 796,
 9,
 868,
 480,
 344,
 329,
 806,
 671,
 649,
 249,
 380,
 621,
 185,
 455,
 606,
 699,
 127,
 483,
 839,
 790,
 312,
 121,
 916,
 679,
 668,
 922,
 892,
 232,
 246,
 436,
 222,
 452,
 854,
 895,
 548,
 897,
 57,
 852,
 546,
 709,
 22,
 765,
 936,
 805,
 766,
 770,
 580,
 613,
 882,
 875,
 459,
 291,
 712,
 899,
 562,
 555,
 889,
 595,
 896,
 586,
 684,
 763,
 601,
 942,
 741,
 756,
 890,
 633,
 840,
 359,
 735,
 447,
 843,
 850,
 188,
 745,
 764,
 738,
 680,
 553,
 603,
 554,
 870,
 804,
 328,
 773,
 197,
 18,
 32,
 566,
 645,
 20,
 577,
 486,
 823,
 759,
 579,
 879,
 7,
 940,
 793,
 938,
 625,
 910,
 894,
 620,
 901,
 798,
 332,
 781,
 908,
 848,
 885,
 686,
 795,
 807,
 183,
 425,
 786,
 937,
 887,
 666,
 588,
 596,
 907,
 933,
 464,
 95,
 41,
 545,
 109,
 715,
 913,
 403,
 723,
 538,
 83,
 307,
 472,
 542,
 924,
 929,
 930,
 560,
 535,
 923,
 800,
 336,
 508,
 693,
 661,
 361,
 921,
 120,
 832,
 943,
 782,
 785,
 893,
 584,
 847,
 838,
 774,
 771,
 497,
 779,
 648,
 734,
 749,
 886,
 739,
 903,
 780,
 301,
 87,
 7,
 62,
 276,
 264,
 295,
 222,
 318,
 293,
 234,
 269,
 379,
 49,
 291,
 442,
 472,
 378,
 336,
 389,
 94,
 5,
 450,
 110,
 307,
 373,
 279,
 13,
 184,
 563,
 200,
 244,
 246,
 453,
 125,
 174,
 38,
 621,
 416,
 314,
 684,
 727,
 796,
 711,
 790,
 399,
 741,
 457,
 881,
 11,
 286,
 823,
 303,
 642,
 435,
 712,
 476,
 804,
 846,
 92,
 405,
 774,
 870,
 864,
 892,
 152,
 927,
 542,
 437,
 833,
 504,
 880,
 805,
 749,
 682,
 943,
 303,
 94,
 286,
 56,
 336,
 416,
 49,
 244,
 455,
 268,
 145,
 184,
 295,
 399,
 11,
 476,
 345,
 790,
 778,
 868,
 712,
 682,
 222,
 927,
 763,
 877,
 405,
 751,
 442,
 709,
 846,
 56,
 303,
 215,
 334,
 38,
 194,
 307,
 7,
 295,
 276,
 290,
 127,
 405,
 374,
 394,
 28,
 337,
 183,
 13,
 267,
 222,
 130,
 145,
 533,
 102,
 44,
 92,
 378,
 70,
 158,
 483,
 532,
 332,
 664,
 600,
 457,
 399,
 275,
 5,
 807,
 437,
 757,
 843,
 497,
 545,
 638,
 603,
 774,
 279,
 584,
 417,
 823,
 650,
 943,
 622,
 268,
 896,
 922,
 95,
 442,
 796,
 536,
 702,
 13,
 7,
 254,
 102,
 405,
 498,
 325,
 472,
 911,
 774,
 504,
 887]

In [67]:
unique_similar_item_user_id=set(similar_item_userid_single_list)

In [68]:
unique_similar_item_user_id

{1,
 2,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 18,
 20,
 21,
 22,
 23,
 25,
 26,
 27,
 28,
 30,
 32,
 37,
 38,
 41,
 42,
 43,
 44,
 45,
 46,
 48,
 49,
 51,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 62,
 63,
 64,
 65,
 66,
 68,
 69,
 70,
 71,
 72,
 77,
 79,
 80,
 82,
 83,
 85,
 87,
 89,
 91,
 92,
 94,
 95,
 96,
 97,
 99,
 101,
 102,
 103,
 104,
 108,
 109,
 110,
 113,
 115,
 116,
 117,
 119,
 120,
 121,
 123,
 124,
 125,
 127,
 128,
 130,
 132,
 137,
 141,
 144,
 145,
 148,
 150,
 151,
 152,
 153,
 154,
 157,
 158,
 160,
 161,
 162,
 169,
 174,
 175,
 176,
 177,
 178,
 182,
 183,
 184,
 185,
 188,
 189,
 192,
 194,
 197,
 198,
 200,
 201,
 203,
 209,
 210,
 213,
 214,
 215,
 216,
 217,
 221,
 222,
 227,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 239,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 253,
 254,
 256,
 257,
 262,
 263,
 264,
 265,
 267,
 268,
 269,
 270,
 271,
 272,
 274,
 275,
 276,
 277,
 279,
 280,
 283,
 286,
 287,
 288,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 301,
 303,
 305,
 307,
 308,
 310,
 311,
 312,
 313,
 314,
 316,
 318,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 332,
 334,
 336,
 337,
 339,
 340,
 343,
 344,
 345,
 346,
 347,
 350,
 352,
 354,
 359,
 360,
 361,
 363,
 367,
 368,
 369,
 370,
 371,
 373,
 374,
 378,
 379,
 380,
 381,
 382,
 385,
 386,
 387,
 389,
 391,
 392,
 393,
 394,
 395,
 397,
 398,
 399,
 401,
 402,
 403,
 405,
 406,
 407,
 409,
 411,
 413,
 416,
 417,
 419,
 421,
 422,
 424,
 425,
 426,
 429,
 430,
 432,
 433,
 435,
 436,
 437,
 438,
 442,
 444,
 445,
 447,
 450,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 461,
 463,
 464,
 465,
 466,
 467,
 468,
 470,
 471,
 472,
 474,
 475,
 476,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 486,
 487,
 488,
 490,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 512,
 513,
 514,
 516,
 517,
 521,
 523,
 524,
 526,
 527,
 528,
 530,
 532,
 533,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 545,
 546,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 557,
 560,
 561,
 562,
 563,
 564,
 566,
 567,
 569,
 573,
 575,
 576,
 577,
 579,
 580,
 581,
 582,
 584,
 586,
 588,
 592,
 593,
 594,
 595,
 596,
 597,
 600,
 601,
 602,
 603,
 606,
 608,
 610,
 613,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 629,
 630,
 632,
 633,
 634,
 637,
 638,
 641,
 642,
 643,
 644,
 645,
 648,
 649,
 650,
 653,
 654,
 655,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 668,
 669,
 671,
 672,
 674,
 676,
 678,
 679,
 680,
 682,
 684,
 686,
 689,
 691,
 693,
 694,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 708,
 709,
 710,
 711,
 712,
 714,
 715,
 716,
 717,
 719,
 721,
 723,
 727,
 730,
 734,
 735,
 736,
 738,
 739,
 741,
 742,
 744,
 745,
 746,
 747,
 748,
 749,
 751,
 753,
 756,
 757,
 758,
 759,
 760,
 761,
 763,
 764,
 765,
 766,
 768,
 770,
 771,
 773,
 774,
 776,
 778,
 779,
 780,
 781,
 782,
 785,
 786,
 789,
 790,
 791,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 804,
 805,
 806,
 807,
 815,
 823,
 825,
 826,
 830,
 831,
 832,
 833,
 834,
 835,
 838,
 839,
 840,
 843,
 844,
 846,
 847,
 848,
 850,
 851,
 852,
 854,
 862,
 864,
 867,
 868,
 869,
 870,
 871,
 875,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 885,
 886,
 887,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 899,
 901,
 902,
 903,
 907,
 908,
 910,
 911,
 913,
 916,
 917,
 919,
 921,
 922,
 923,
 924,
 927,
 929,
 930,
 931,
 933,
 934,
 936,
 937,
 938,
 940,
 942,
 943}

In [52]:
#Similiarly check for paricular movie_id
input_item_watched_list=list(rating[rating['movie_id']==input_item]['user_id'])

In [54]:
len(input_item_watched_list)

583

In [69]:
#Find the find the recommandation list means filtering out the watched item from input item of user id comparing with similiar input item list

recom_list=[]
for movie_id in unique_similar_item_user_id:
    if movie_id in input_item_watched_list:
        pass
    else:
        recom_list.append(movie_id)

In [70]:
sorted(recom_list)

[11, 38, 110, 152, 264, 314, 442, 476, 532, 702, 778, 877, 911, 927]

In [71]:
sorted(unique_similar_item_user_id)

[1,
 2,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 18,
 20,
 21,
 22,
 23,
 25,
 26,
 27,
 28,
 30,
 32,
 37,
 38,
 41,
 42,
 43,
 44,
 45,
 46,
 48,
 49,
 51,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 62,
 63,
 64,
 65,
 66,
 68,
 69,
 70,
 71,
 72,
 77,
 79,
 80,
 82,
 83,
 85,
 87,
 89,
 91,
 92,
 94,
 95,
 96,
 97,
 99,
 101,
 102,
 103,
 104,
 108,
 109,
 110,
 113,
 115,
 116,
 117,
 119,
 120,
 121,
 123,
 124,
 125,
 127,
 128,
 130,
 132,
 137,
 141,
 144,
 145,
 148,
 150,
 151,
 152,
 153,
 154,
 157,
 158,
 160,
 161,
 162,
 169,
 174,
 175,
 176,
 177,
 178,
 182,
 183,
 184,
 185,
 188,
 189,
 192,
 194,
 197,
 198,
 200,
 201,
 203,
 209,
 210,
 213,
 214,
 215,
 216,
 217,
 221,
 222,
 227,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 239,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 253,
 254,
 256,
 257,
 262,
 263,
 264,
 265,
 267,
 268,
 269,
 270,
 271,
 272,
 274,
 275,
 276,
 277,
 279,
 280,
 283,
 286,
 287,
 288,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 301,
 303,
 305,
 307,
 308,
 310,
 311,
 312,
 313,
 314,
 316,
 318,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 332,
 334,
 336,
 337,
 339,
 340,
 343,
 344,
 345,
 346,
 347,
 350,
 352,
 354,
 359,
 360,
 361,
 363,
 367,
 368,
 369,
 370,
 371,
 373,
 374,
 378,
 379,
 380,
 381,
 382,
 385,
 386,
 387,
 389,
 391,
 392,
 393,
 394,
 395,
 397,
 398,
 399,
 401,
 402,
 403,
 405,
 406,
 407,
 409,
 411,
 413,
 416,
 417,
 419,
 421,
 422,
 424,
 425,
 426,
 429,
 430,
 432,
 433,
 435,
 436,
 437,
 438,
 442,
 444,
 445,
 447,
 450,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 461,
 463,
 464,
 465,
 466,
 467,
 468,
 470,
 471,
 472,
 474,
 475,
 476,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 486,
 487,
 488,
 490,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 512,
 513,
 514,
 516,
 517,
 521,
 523,
 524,
 526,
 527,
 528,
 530,
 532,
 533,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 545,
 546,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 557,
 560,
 561,
 562,
 563,
 564,
 566,
 567,
 569,
 573,
 575,
 576,
 577,
 579,
 580,
 581,
 582,
 584,
 586,
 588,
 592,
 593,
 594,
 595,
 596,
 597,
 600,
 601,
 602,
 603,
 606,
 608,
 610,
 613,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 629,
 630,
 632,
 633,
 634,
 637,
 638,
 641,
 642,
 643,
 644,
 645,
 648,
 649,
 650,
 653,
 654,
 655,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 668,
 669,
 671,
 672,
 674,
 676,
 678,
 679,
 680,
 682,
 684,
 686,
 689,
 691,
 693,
 694,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 708,
 709,
 710,
 711,
 712,
 714,
 715,
 716,
 717,
 719,
 721,
 723,
 727,
 730,
 734,
 735,
 736,
 738,
 739,
 741,
 742,
 744,
 745,
 746,
 747,
 748,
 749,
 751,
 753,
 756,
 757,
 758,
 759,
 760,
 761,
 763,
 764,
 765,
 766,
 768,
 770,
 771,
 773,
 774,
 776,
 778,
 779,
 780,
 781,
 782,
 785,
 786,
 789,
 790,
 791,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 804,
 805,
 806,
 807,
 815,
 823,
 825,
 826,
 830,
 831,
 832,
 833,
 834,
 835,
 838,
 839,
 840,
 843,
 844,
 846,
 847,
 848,
 850,
 851,
 852,
 854,
 862,
 864,
 867,
 868,
 869,
 870,
 871,
 875,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 885,
 886,
 887,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 899,
 901,
 902,
 903,
 907,
 908,
 910,
 911,
 913,
 916,
 917,
 919,
 921,
 922,
 923,
 924,
 927,
 929,
 930,
 931,
 933,
 934,
 936,
 937,
 938,
 940,
 942,
 943]

In [73]:
list(set(unique_similar_item_user_id)&set(input_item_watched_list))

[1,
 2,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 12,
 13,
 14,
 15,
 18,
 20,
 21,
 22,
 23,
 25,
 26,
 27,
 28,
 30,
 32,
 37,
 41,
 42,
 43,
 44,
 45,
 46,
 48,
 49,
 51,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 62,
 63,
 64,
 65,
 66,
 68,
 69,
 70,
 71,
 72,
 77,
 79,
 80,
 82,
 83,
 85,
 87,
 89,
 91,
 92,
 94,
 95,
 96,
 97,
 99,
 101,
 102,
 103,
 104,
 108,
 109,
 113,
 115,
 116,
 117,
 119,
 120,
 121,
 123,
 124,
 125,
 127,
 128,
 130,
 132,
 137,
 141,
 144,
 145,
 148,
 150,
 151,
 153,
 154,
 157,
 158,
 160,
 161,
 162,
 169,
 174,
 175,
 176,
 177,
 178,
 182,
 183,
 184,
 185,
 188,
 189,
 192,
 194,
 197,
 198,
 200,
 201,
 203,
 209,
 210,
 213,
 214,
 215,
 216,
 217,
 221,
 222,
 227,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 239,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 253,
 254,
 256,
 257,
 262,
 263,
 265,
 267,
 268,
 269,
 270,
 271,
 272,
 274,
 275,
 276,
 277,
 279,
 280,
 283,
 286,
 287,
 288,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 301,
 303,
 305,
 307,
 308,
 310,
 311,
 312,
 313,
 316,
 318,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 332,
 334,
 336,
 337,
 339,
 340,
 343,
 344,
 345,
 346,
 347,
 350,
 352,
 354,
 359,
 360,
 361,
 363,
 367,
 368,
 369,
 370,
 371,
 373,
 374,
 378,
 379,
 380,
 381,
 382,
 385,
 386,
 387,
 389,
 391,
 392,
 393,
 394,
 395,
 397,
 398,
 399,
 401,
 402,
 403,
 405,
 406,
 407,
 409,
 411,
 413,
 416,
 417,
 419,
 421,
 422,
 424,
 425,
 426,
 429,
 430,
 432,
 433,
 435,
 436,
 437,
 438,
 444,
 445,
 447,
 450,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 461,
 463,
 464,
 465,
 466,
 467,
 468,
 470,
 471,
 472,
 474,
 475,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 486,
 487,
 488,
 490,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 512,
 513,
 514,
 516,
 517,
 521,
 523,
 524,
 526,
 527,
 528,
 530,
 533,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 545,
 546,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 557,
 560,
 561,
 562,
 563,
 564,
 566,
 567,
 569,
 573,
 575,
 576,
 577,
 579,
 580,
 581,
 582,
 584,
 586,
 588,
 592,
 593,
 594,
 595,
 596,
 597,
 600,
 601,
 602,
 603,
 606,
 608,
 610,
 613,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 629,
 630,
 632,
 633,
 634,
 637,
 638,
 641,
 642,
 643,
 644,
 645,
 648,
 649,
 650,
 653,
 654,
 655,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 668,
 669,
 671,
 672,
 674,
 676,
 678,
 679,
 680,
 682,
 684,
 686,
 689,
 691,
 693,
 694,
 697,
 698,
 699,
 700,
 701,
 703,
 704,
 705,
 706,
 708,
 709,
 710,
 711,
 712,
 714,
 715,
 716,
 717,
 719,
 721,
 723,
 727,
 730,
 734,
 735,
 736,
 738,
 739,
 741,
 742,
 744,
 745,
 746,
 747,
 748,
 749,
 751,
 753,
 756,
 757,
 758,
 759,
 760,
 761,
 763,
 764,
 765,
 766,
 768,
 770,
 771,
 773,
 774,
 776,
 779,
 780,
 781,
 782,
 785,
 786,
 789,
 790,
 791,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 804,
 805,
 806,
 807,
 815,
 823,
 825,
 826,
 830,
 831,
 832,
 833,
 834,
 835,
 838,
 839,
 840,
 843,
 844,
 846,
 847,
 848,
 850,
 851,
 852,
 854,
 862,
 864,
 867,
 868,
 869,
 870,
 871,
 875,
 878,
 879,
 880,
 881,
 882,
 883,
 885,
 886,
 887,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 899,
 901,
 902,
 903,
 907,
 908,
 910,
 913,
 916,
 917,
 919,
 921,
 922,
 923,
 924,
 929,
 930,
 931,
 933,
 934,
 936,
 937,
 938,
 940,
 942,
 943]

In [83]:
#Create teh dataframe for item prediction
item_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.446278,0.475473,0.505938,0.443633,0.512667,0.547939,0.446243,0.463059,0.474916,0.515821,...,0.580579,0.576202,0.582478,0.582478,0.575717,0.588155,0.588155,0.588155,0.573107,0.566696
2,0.108544,0.132957,0.125589,0.124932,0.131178,0.129005,0.110883,0.122223,0.109599,0.121525,...,0.135490,0.136546,0.134829,0.134829,0.134108,0.134458,0.134458,0.134458,0.136576,0.137111
3,0.085685,0.091690,0.087643,0.089966,0.089658,0.089985,0.083492,0.089725,0.085188,0.088331,...,0.089770,0.090506,0.086261,0.086261,0.089201,0.084659,0.084659,0.084659,0.089768,0.090845
4,0.053693,0.059604,0.058114,0.058364,0.059356,0.061472,0.053374,0.058615,0.055905,0.060601,...,0.061349,0.061686,0.061195,0.061195,0.060693,0.057937,0.057937,0.057937,0.061673,0.062281
5,0.224739,0.229171,0.263280,0.226387,0.259973,0.296529,0.232710,0.237109,0.258581,0.275076,...,0.297628,0.295990,0.299922,0.299922,0.298188,0.302051,0.302051,0.302051,0.293373,0.294309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.092574,0.113870,0.110211,0.112040,0.112768,0.123140,0.098578,0.110839,0.098858,0.118579,...,0.123829,0.124430,0.120776,0.120776,0.121360,0.125056,0.125056,0.125056,0.123470,0.124327
940,0.164358,0.184894,0.196502,0.164884,0.195860,0.209652,0.162840,0.165606,0.171761,0.194536,...,0.217536,0.215515,0.219136,0.219136,0.216173,0.218583,0.218583,0.218583,0.216582,0.216819
941,0.032300,0.045024,0.042924,0.043223,0.047493,0.051077,0.032761,0.042646,0.039399,0.047421,...,0.052762,0.053042,0.052692,0.052692,0.051514,0.053028,0.053028,0.053028,0.051910,0.052280
942,0.157779,0.174095,0.189000,0.163514,0.186140,0.194151,0.164910,0.156970,0.167038,0.181295,...,0.197537,0.194479,0.198479,0.198479,0.197969,0.199793,0.199793,0.199793,0.197394,0.200031
943,0.247672,0.244892,0.282630,0.241440,0.279338,0.335121,0.250015,0.263325,0.273579,0.313885,...,0.336816,0.338652,0.338585,0.338585,0.336956,0.344104,0.344104,0.344104,0.330514,0.331025

In [87]:
item_pred=pd.DataFrame(item_pred[input_item])

In [88]:
item_pred

               50
user_id
1        0.499834
2        0.130727
3        0.090523
4        0.059385
5        0.254289
...           ...
939      0.114022
940      0.189215
941      0.048535
942      0.176553
943      0.270710

[943 rows x 1 columns]

In [89]:
# Checking the common movie list
list(set(recom_list)&set(input_item_watched_userid))

In [92]:
item_pred_trans[70].values

array([0.22280584])

In [101]:
recom_list

[11, 38, 110, 152, 264, 314, 442, 476, 532, 702, 778, 877, 911, 927]

In [102]:
# From recomd list select hightest rated film which would like by the user. Based on User prediction

highest_rated = []
for re in recom_list:
    value = item_pred_trans[re].values
    if value >= 0.3:
         highest_rated.append(re)

In [103]:
highest_rated

[11, 314, 532]

In [105]:
# Checking the common movie list
list(set(recom_list)&set(input_item_watched_list))

[]

In [106]:
def itembased(input_item,item_similarity,item_predictions,similar_item_count,thres):
    #Convert the user_sim table into DataFrame
    item_sim_table=pd.DataFrame(item_similarity)
    #Find similarity user for 78 using cosine table
    similar_input_item= item_sim_table[input_item].sort_values(ascending=True).head(similar_item_count).index
    #Convert in to list
    similar_item_input=list(similar_input_item) 
    #Using similar_user_input,can select movie id from ratings table
    similar_item_userid_list=[]
    for sim_item in similar_item_input:
        sim=list(ratings[ratings['movie_id']==sim_item]['user_id'])
        similar_item_userid_list.append(sim)
    #Converting as a whole list
    import itertools
    similar_item_userid_single_list=list(itertools.chain.from_iterable(similar_item_userid_list))
    #Unique movieid from the list
    Unique_userid_similar_item=set(similar_item_userid_single_list)
    #Input user watched movie_list
    input_item_watched_userid=list(ratings[ratings['movie_id']==input_item]['user_id'].values)
    #Create a list which should have recom movieid to the input user
    recom=[]
    for per_id in Unique_userid_similar_item:
        if(per_id in input_item_watched_userid):
            pass
        else:
            recom.append(per_id)
    #From recommendation list selecting only hightest rated(predicted) value
    highest_Rated=[]
    user_pred=pd.DataFrame(item_prediction)
    input_item_pre=pd.DataFrame(user_pred[input_item])
    input_item_pred=input_item_pre.T
    for re in recom:
        value=input_item_pred[re].values
        if(value>=thres):
            highest_Rated.append(re)
    highest_Rated
    return highest_Rated